# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'DeadlySyn Blog'
tagline:             'Strong opinions, weakly held.'
description:         'DevOps, space travel, automobiles, gadgets, and other random babblings...'
url:                 http://deadlysyn.github.io
baseurl:             '/blog'
production_url:      http://deadlysyn.github.io.com/blog
BASE_PATH:           http://deadlysyn.com/blog
paginate:            5

# About/contact
author:
  name:              Mike Hoskins
  url:               http://deadlysyn.com
  email:             unixdoes@gmail.com

# Custom vars
version:             1.0.0
