title:               "Noisy Neighbor"
tagline:             "Perfect is a verb, not a noun."
description:         "DevOps, SRE, coding, and other random babblings..."
baseurl:             "/blog"
url:                 "http://deadlysyn.com"
production_url:      "http://deadlysyn.com"
#BASE_PATH:           http://deadlysyn.com/blog
paginate:            3
permalink:           "pretty"
publish:             true
timezone:            "America/New_York"

# Custom vars
version:             "1.0.3"

# About/contact
author:
  name:              "Mike Hoskins"
  url:               "http://deadlysyn.com"
  email:             "unixdoes@gmail.com"
  github:            "https://github.com/deadlysyn"
  linkedin:          "https://www.linkedin.com/in/mikehoskins"

prose:
  rooturl:           "_posts"
  siteurl:           "http://deadlysyn.com/"
  relativeLinks:     "http://deadlysyn.com/links.jsonp"
  media:             "media"
  ignore:
    - atom.xml
    - index.html
    - 404.html
    - _config.yml
    - /_includes
    - /_layouts
    - /public
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "hidden"
          value: "Mike Hoskins"
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "category"
        field:
          element: "select"
          label: "Select Category"
          placeholder: "Choose Category"
          options:
            - name: "Apple"
              value: "apple"
            - name: "Blog Post"
              value: "blog"
            - name: "Cars"
              value: "cars"
            - name: "Cloud"
              value: "cloud"
            - name: "Development"
              value: "development"
            - name: "Security"
              value: "security"
            - name: "Space"
              value: "space"
            - name: "UNIX"
              value: "unix"
            - name: "Work"
              value: "work"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Backend"
              value: "backend"
            - name: "CI/CD"
              value: "cicd"
            - name: "CLI"
              value: "cli"
            - name: "Computing"
              value: "computing"
            - name: "Docker"
              value: "docker"
            - name: "Frontend"
              value: "frontend"
            - name: "Golang"
              value: "golang"
            - name: "Humor"
              value: "humor"
            - name: "Javascript"
              value: "javascript"
            - name: "Monitoring"
              value: "monitoring"
            - name: "Python"
              value: "python"
            - name: "SRE"
              value: "sre"
            - name: "TDD"
              value: "tdd"
            - name: "UNIX"
              value: "unix"
            - name: "Web"
              value: "web"
